name: Build and push latest Playwright, Allure docker image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Запускать каждый день в полночь

jobs:
  build_Playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build playwrite Docker Image
        run: |
          playwright_version=$(basename $(curl -s "https://api.github.com/repos/microsoft/playwright-python/releases/latest" | jq -r '.zipball_url'))
          playwright_version="${playwright_version:1}"
          latest_docker_version=$(curl -s "https://hub.docker.com/v2/repositories/vgoroshenko/playwright/tags/?page_size=1" | jq -r '.results[0].name')
          
          if [[ $playwright_version == *$latest_docker_version ]]; then
              echo "Версия Playwrigh актуальна $latest_docker_version"
          else 
              docker build -t vgoroshenko/playwright:$playwright_version -f cicd/pl.Dockerfile .
              docker push vgoroshenko/playwright:$playwright_version
          fi

  build_Allure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build allure Docker Image
        run: |
          allure_version=$(basename $(curl -s "https://api.github.com/repos/allure-framework/allure2/releases/latest" | jq -r '.zipball_url'))
          latest_docker_version=$(curl -s "https://hub.docker.com/v2/repositories/vgoroshenko/allure/tags/?page_size=1" | jq -r '.results[0].name')          
                    
          if [[ $allure_version == *$latest_docker_version ]]; then
              echo "Версия Allure актуальна $latest_docker_version"
          else
              sed -i "s/ALLUREVER/$allure_version/g" Dockerfile
              docker build -t vgoroshenko/allure:$allure_version .
              docker push vgoroshenko/allure:$allure_version
          fi
