name: Test and Deploy result from Docker
on:
  workflow_dispatch:
jobs:
  test build:
    needs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start web server
        run: |
          docker-compose -f "docker-compose.yml" up -d

      - name: Run test
        run: |
          docker run -v .:/app vgoroshenko/playwright sh -c "pip install  -r requirements.txt; pytest"

      - name: Run generate allure report
        run: |
          docker run -v .:/app vgoroshenko/allure sh -c "allure generate reports"

      - name: Stop web server
        if: always()
        run: |
          docker-compose -f "docker-compose.yml" down --rmi all

      - name: Deploy report🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: allure-report
          clean: false