name: Test playwright
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: microsoft/playwright-github-action@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: |
          sudo apt install make
          make pull
          docker-compose -f "docker-compose.yml" up -d

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure browsers are installed
        run: playwright install

      - name: Run your tests
        run:  pytest -s -v --tb=line --browser webkit --browser firefox --browser chromium -n 5 --alluredir=reports -q

      - name: Generate report
        if: always()
        run: |
          sudo mkdir /allure
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.tgz
          sudo tar zxf allure-2.17.2.tgz -C /allure
          export PATH="/allure/allure-2.17.2/bin:${PATH}"
          allure generate reports

      - name: Stop containers
        if: always()
        run: |
          docker-compose -f "docker-compose.yml" down -rm
          make clean

      - name: Deploy report🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: allure-report
          clean: false
