name: Test and Deploy result from Python
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start web server
        run: |
          docker-compose -f "docker-compose.yml" up -d

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install --with-deps

      - name: Test with pytest
        run: |
          pytest

      - name: Generate report
        if: always()
        run: |
          sudo mkdir /allure
          archive_name=$(basename $(curl -s "https://api.github.com/repos/allure-framework/allure2/releases/latest" | jq -r '.zipball_url'))
          sudo wget https://github.com/allure-framework/allure2/releases/download/$archive_name/allure-$archive_name.tgz
          sudo tar zxf allure-$archive_name.tgz -C /allure
          export PATH="/allure/allure-$archive_name/bin:${PATH}"
          allure generate reports

      - name: Stop web server
        if: always()
        run: |
          docker-compose -f "docker-compose.yml" down --rmi all

      - name: Deploy report🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: allure-report
          clean: false
